<?php
require __DIR__ . '/bootstrap.php';
use Sharesl\Original\MailForm\OMF_Form_Builder as Builder;
use Sharesl\Original\MailForm\OMF_Field_Schema as Schema;
$fields = [['key'=>'email','label'=>'メール','type'=>'email','required'=>true], ['key'=>'message','label'=>'本文','type'=>'textarea']];
$schema = ['version'=>1,'fields'=>$fields];
$input = ['omf_builder_mode'=>'builder','omf_builder_schema'=>json_encode($schema)];
$prepared = Builder::prepare(10,$input);
check(is_array($prepared), '正しい項目定義を保存用に正規化');
Builder::persist(10,$prepared);
check(Schema::mode(10)==='builder' && array_column(Schema::read(10)['fields'],'key')===['email','message'], '保存後に方式・項目・順序を復元');
$input['omf_front_validation']='1';
Builder::persist(10,Builder::prepare(10,$input));
check(get_post_meta(10,'cf_omf_front_validation',true)==='1', 'フォーム別のJS検証ONを保存');
$input['omf_front_validation']='invalid';
check(is_wp_error(Builder::prepare(10,$input)), 'JS検証の不正な設定を拒否');
$input['omf_front_validation']='0';
Builder::persist(10,Builder::prepare(10,$input));
check(get_post_meta(10,'cf_omf_front_validation',true)==='0', 'JS検証OFFへ戻せる');
$schema['fields']=array_reverse($fields);$input['omf_builder_schema']=json_encode($schema);
Builder::persist(10,Builder::prepare(10,$input));
check(array_column(Schema::read(10)['fields'],'key')===['message','email'], '並べ替えが保存される');
$before=$GLOBALS['meta'];$input['omf_builder_schema']='broken';
check(is_wp_error(Builder::prepare(10,$input)) && $before===$GLOBALS['meta'], '壊れたJSONは保存済み定義を変更しない');
$schema['fields']=[array_replace($fields[0],['key'=>'changed','original_key'=>'email'])];$input['omf_builder_schema']=json_encode($schema);
check(is_wp_error(Builder::prepare(10,$input)), '保存済みキーの書き換えを拒否');
$schema['fields']=[$fields[1]];$input['omf_builder_schema']=json_encode($schema);
$GLOBALS['meta'][10]['cf_omf_reply_to']='{email}';
check(is_wp_error(Builder::prepare(10,$input)), 'メール宛先で参照中の項目を削除できない');
$input['cf_omf_reply_to']='fixed@example.test';
check(is_array(Builder::prepare(10,$input)), '同じ保存でメール参照を外した場合だけ削除できる');
$schema['fields']=[$fields[0],$fields[0]];$input['omf_builder_schema']=json_encode($schema);
check(is_wp_error(Builder::prepare(10,$input)), '重複キーを保存前に拒否');
check(Builder::prepare(10,[])===null, 'ビルダー入力なしでは既存保存経路を維持');
$input=['omf_builder_mode'=>'code','omf_builder_schema'=>json_encode(['version'=>1,'fields'=>[]]),'cf_omf_reply_to'=>''];
check(is_array(Builder::prepare(10,$input)), 'コード方式は未使用の空定義を許容');
$input['omf_builder_mode']='builder';
check(is_wp_error(Builder::prepare(10,$input)), '管理画面方式は空の項目一覧を拒否');
$GLOBALS['meta'][10][Schema::MODE_KEY]='code';
$GLOBALS['meta'][10]['cf_omf_validation']=[['target'=>'legacy_email','email'=>'1']];
$input['omf_builder_schema']=json_encode(['version'=>1,'fields'=>$fields]);$input['cf_omf_reply_to']='{legacy_email}';
check(is_wp_error(Builder::prepare(10,$input)), '方式切り替えで旧メールタグの参照先を消失させない');
$input = ['omf_builder_mode'=>'builder','omf_builder_schema'=>json_encode(['version'=>1,'fields'=>$fields]),'omf_complete_message'=>"受付完了\n担当者から連絡します。<script>alert(1)</script>"];
$prepared = Builder::prepare(11,$input); Builder::persist(11,$prepared);
check(get_post_meta(11,'cf_omf_complete_message',true)==="受付完了\n担当者から連絡します。alert(1)", '完了メッセージは改行を保存しHTMLを除去');
$input['omf_complete_message']=[];
check(is_wp_error(Builder::prepare(11,$input)), '完了メッセージの配列入力を拒否');
$input['omf_complete_message']=''; Builder::persist(11,Builder::prepare(11,$input));
check(get_post_meta(11,'cf_omf_complete_message',true)==='', '完了メッセージを空欄へ戻せる');
echo "管理画面保存テスト完了\n";
